
package soap.register;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRegisterService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRegisterService {


    /**
     * 
     * @param password
     * @param username
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/IRegisterService/Register")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "soap.register.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "soap.register.RegisterResponse")
    public void register(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param username
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AccountExists", action = "http://tempuri.org/IRegisterService/AccountExists")
    @WebResult(name = "AccountExistsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AccountExists", targetNamespace = "http://tempuri.org/", className = "soap.register.AccountExists")
    @ResponseWrapper(localName = "AccountExistsResponse", targetNamespace = "http://tempuri.org/", className = "soap.register.AccountExistsResponse")
    public Boolean accountExists(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneratePassword", action = "http://tempuri.org/IRegisterService/GeneratePassword")
    @WebResult(name = "GeneratePasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneratePassword", targetNamespace = "http://tempuri.org/", className = "soap.register.GeneratePassword")
    @ResponseWrapper(localName = "GeneratePasswordResponse", targetNamespace = "http://tempuri.org/", className = "soap.register.GeneratePasswordResponse")
    public String generatePassword();

}
