
package soap.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserService {


    /**
     * 
     * @param username
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "GetMoney", action = "http://tempuri.org/IUserService/GetMoney")
    @WebResult(name = "GetMoneyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMoney", targetNamespace = "http://tempuri.org/", className = "soap.user.GetMoney")
    @ResponseWrapper(localName = "GetMoneyResponse", targetNamespace = "http://tempuri.org/", className = "soap.user.GetMoneyResponse")
    public Double getMoney(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param productName
     * @param username
     */
    @WebMethod(operationName = "AddProduct", action = "http://tempuri.org/IUserService/AddProduct")
    @RequestWrapper(localName = "AddProduct", targetNamespace = "http://tempuri.org/", className = "soap.user.AddProduct")
    @ResponseWrapper(localName = "AddProductResponse", targetNamespace = "http://tempuri.org/", className = "soap.user.AddProductResponse")
    public void addProduct(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "productName", targetNamespace = "http://tempuri.org/")
        String productName);

    /**
     * 
     * @param productName
     * @param username
     */
    @WebMethod(operationName = "RemoveProduct", action = "http://tempuri.org/IUserService/RemoveProduct")
    @RequestWrapper(localName = "RemoveProduct", targetNamespace = "http://tempuri.org/", className = "soap.user.RemoveProduct")
    @ResponseWrapper(localName = "RemoveProductResponse", targetNamespace = "http://tempuri.org/", className = "soap.user.RemoveProductResponse")
    public void removeProduct(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "productName", targetNamespace = "http://tempuri.org/")
        String productName);

    /**
     * 
     * @param username
     * @return
     *     returns soap.user.ArrayOfProductItem
     */
    @WebMethod(operationName = "GetProductItems", action = "http://tempuri.org/IUserService/GetProductItems")
    @WebResult(name = "GetProductItemsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProductItems", targetNamespace = "http://tempuri.org/", className = "soap.user.GetProductItems")
    @ResponseWrapper(localName = "GetProductItemsResponse", targetNamespace = "http://tempuri.org/", className = "soap.user.GetProductItemsResponse")
    public ArrayOfProductItem getProductItems(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

}
